spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crawler?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 666666
  redis:
    database: 0 #Redis数据库索引（默认为0）
    host: 127.0.0.1 #192.168.1.2 #Redis服务器地址
    lettuce:
      pool:
        max-active: 20 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 5 #连接池中的最大空闲连接
        max-wait: -1 #最大阻塞等待时间(负数表示没限制)
        min-idle: 0 #连接池中的最小空闲连接
    port: 6379 #配置spring启动端口号
    timeout: 1800000 #连接超时时间（毫秒）
server:
  port: 9090
